# ===========================================================================
# Project:   Todos
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
#
#
config :all, :html5_manifest => [:all]

config :foundation, :required => []
config :local, :required => [:foundation]
config :irich, :required => [:local]
config :all, :required => [:sproutcore, :irich]
